export const styles = {
  container: { display: 'flex', justifyContent: 'center', mt: 4 },
  stack: { width: '100%', maxWidth: 400 },
  card: { p: 3, boxShadow: 'md', width: '100%' },
  sheet: { width: 365, p: 2, borderRadius: 'sm' },
  list: { maxHeight: 300, overflowY: 'auto' },
  cardOverflow: { display: 'flex', justifyContent: 'flex-end', p: 2 },
  cardActions: { display: 'flex', justifyContent: 'flex-end' },
  avatarBox: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 1, mb: 2 },
  avatar: { width: 80, height: 80 },
  uploadButton: { display: 'none' },
  doneIcon: { position: 'absolute', left: 8, top: '50%', transform: 'translateY(-50%)' },
  headerWithSearch: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 1.5 },
  title: { fontWeight: 'lg' },
  searchField: { ml: 2, width: 150 },
  titleVolunteerOptions: { fontWeight: "lg", mb: 2, textAlign: "center" },
  categoryBox: { mb: 2 },
  categoryTitle: { fontWeight: "lg", mb: 1 },
  listItems: { "--List-gap": "8px", "--ListItem-radius": "20px" },
};
